dist: trusty
language: node_js
node_js:
- '6'
before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - npm install -g bower web-component-tester
  - bower install
script: xvfb-run wct
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable